import { useContext, useEffect } from "react";
import NavBar from "./NavBar";
import { AuthContext } from "../hooks/AuthContext";
import URI from "../uri";

export default function Home() {
	const Auth = useContext(AuthContext);
	const Uri = new URI();
	const token = localStorage.getItem('mario-blog-key') || undefined;

	useEffect(() => {
		if(token === undefined) {
			return;
		}

		const abort = new AbortController();
		async function getAuth() {
			try {
				const response = await fetch(Uri.auth, { 
					signal: abort.signal,
					mode: 'cors',
					headers: { 'Authorization' : `BEARER: ${token}` },
				});
				const resData = await response.json();
				if (resData.success) {
					Auth?.logIn(resData.data);
				}
			} catch(error) {
				console.log(error);
			}
		}

		getAuth();

		return () => {
			abort.abort();
		}
	}, []);

	return (
	<div>
		<NavBar />
		<h1 className="text-white">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tristique senectus et netus et malesuada fames ac turpis egestas. Adipiscing elit pellentesque habitant morbi tristique senectus et netus. Enim blandit volutpat maecenas volutpat blandit. Orci eu lobortis elementum nibh. Et tortor consequat id porta nibh venenatis. Nibh nisl condimentum id venenatis a condimentum vitae sapien. Vitae proin sagittis nisl rhoncus. Ut tellus elementum sagittis vitae et leo duis ut. In vitae turpis massa sed elementum tempus. Suspendisse potenti nullam ac tortor vitae purus faucibus ornare suspendisse. Lorem ipsum dolor sit amet consectetur adipiscing elit ut aliquam. Id neque aliquam vestibulum morbi blandit. Aliquam vestibulum morbi blandit cursus risus at ultrices. Mi proin sed libero enim sed faucibus turpis in eu. Lacus suspendisse faucibus interdum posuere lorem ipsum.

Vel orci porta non pulvinar neque. In hac habitasse platea dictumst quisque sagittis. Orci ac auctor augue mauris augue neque gravida. Nec sagittis aliquam malesuada bibendum arcu vitae elementum. Ultricies mi eget mauris pharetra et ultrices neque. Faucibus pulvinar elementum integer enim neque volutpat ac. Iaculis eu non diam phasellus. Risus sed vulputate odio ut enim blandit volutpat maecenas volutpat. In ornare quam viverra orci sagittis eu volutpat odio facilisis. Eget velit aliquet sagittis id consectetur purus ut faucibus. Turpis egestas sed tempus urna. Sollicitudin ac orci phasellus egestas tellus. Orci nulla pellentesque dignissim enim sit amet venenatis urna. Pretium aenean pharetra magna ac placerat. Malesuada fames ac turpis egestas maecenas pharetra convallis.

Commodo sed egestas egestas fringilla phasellus faucibus scelerisque. Elit at imperdiet dui accumsan sit. Diam sollicitudin tempor id eu. Leo urna molestie at elementum eu facilisis. Mattis ullamcorper velit sed ullamcorper morbi tincidunt ornare massa eget. Lorem donec massa sapien faucibus et molestie ac feugiat. Et pharetra pharetra massa massa ultricies mi. Rhoncus dolor purus non enim praesent elementum. Proin gravida hendrerit lectus a. Turpis egestas sed tempus urna et pharetra. Mauris ultrices eros in cursus. Facilisis gravida neque convallis a cras semper auctor. Et tortor at risus viverra adipiscing at. Phasellus faucibus scelerisque eleifend donec pretium. Ullamcorper malesuada proin libero nunc. Sapien pellentesque habitant morbi tristique senectus et. Semper viverra nam libero justo laoreet sit amet cursus sit. Ultricies mi quis hendrerit dolor magna eget est lorem. Pellentesque sit amet porttitor eget dolor.

Blandit volutpat maecenas volutpat blandit aliquam. Rhoncus urna neque viverra justo nec ultrices dui sapien eget. Tristique senectus et netus et. Sed libero enim sed faucibus turpis in eu. Ullamcorper a lacus vestibulum sed arcu. Volutpat odio facilisis mauris sit. Consequat ac felis donec et odio pellentesque diam volutpat commodo. Magna etiam tempor orci eu lobortis elementum nibh tellus. Cras ornare arcu dui vivamus arcu felis bibendum ut. Sed adipiscing diam donec adipiscing tristique. Diam maecenas ultricies mi eget mauris pharetra et.

Ut sem nulla pharetra diam. Nunc congue nisi vitae suscipit. Ante metus dictum at tempor commodo ullamcorper a. Quam adipiscing vitae proin sagittis. Quis auctor elit sed vulputate mi sit amet mauris commodo. Amet cursus sit amet dictum sit amet justo donec. Urna neque viverra justo nec ultrices dui. Maecenas volutpat blandit aliquam etiam erat velit. Sit amet nisl suscipit adipiscing bibendum est ultricies integer quis. Egestas erat imperdiet sed euismod. Nisi est sit amet facilisis magna etiam tempor.

Nullam non nisi est sit. Aliquam sem fringilla ut morbi tincidunt augue interdum velit. Pharetra magna ac placerat vestibulum lectus mauris ultrices eros in. Blandit cursus risus at ultrices mi tempus imperdiet. Arcu cursus euismod quis viverra nibh cras. Tincidunt dui ut ornare lectus. Integer feugiat scelerisque varius morbi enim nunc faucibus a pellentesque. Id cursus metus aliquam eleifend mi in nulla posuere sollicitudin. Volutpat lacus laoreet non curabitur gravida arcu. Fames ac turpis egestas sed tempus urna et. In arcu cursus euismod quis viverra nibh cras pulvinar. Sed enim ut sem viverra aliquet eget sit amet tellus. Adipiscing diam donec adipiscing tristique risus nec feugiat in fermentum. Amet consectetur adipiscing elit duis tristique. Nisl pretium fusce id velit. Nunc mi ipsum faucibus vitae aliquet nec. Pharetra pharetra massa massa ultricies. Augue neque gravida in fermentum et sollicitudin ac orci phasellus. Posuere ac ut consequat semper viverra nam libero. Fermentum posuere urna nec tincidunt praesent semper feugiat nibh sed.

Pellentesque dignissim enim sit amet venenatis urna cursus. At tellus at urna condimentum mattis pellentesque id nibh tortor. Ultrices neque ornare aenean euismod elementum. Aenean sed adipiscing diam donec adipiscing. Erat velit scelerisque in dictum non consectetur a erat. Eu feugiat pretium nibh ipsum consequat nisl. Nulla facilisi cras fermentum odio eu feugiat pretium nibh. Libero nunc consequat interdum varius sit amet. Nunc vel risus commodo viverra maecenas accumsan lacus. Risus sed vulputate odio ut enim blandit. Velit egestas dui id ornare. Id volutpat lacus laoreet non curabitur gravida arcu ac tortor. Diam quam nulla porttitor massa id neque aliquam vestibulum morbi. Tortor aliquam nulla facilisi cras fermentum odio eu feugiat. Aliquet nibh praesent tristique magna sit amet purus gravida. Odio morbi quis commodo odio aenean sed. Commodo viverra maecenas accumsan lacus vel facilisis volutpat est velit. Consequat semper viverra nam libero justo laoreet.

Pharetra vel turpis nunc eget. At tempor commodo ullamcorper a. At auctor urna nunc id cursus metus aliquam. Tellus orci ac auctor augue. Congue nisi vitae suscipit tellus mauris a diam maecenas. Aliquet enim tortor at auctor urna nunc id. Auctor elit sed vulputate mi sit amet. Eget duis at tellus at urna. Morbi blandit cursus risus at ultrices mi. Varius duis at consectetur lorem donec massa sapien. Congue quisque egestas diam in arcu cursus euismod quis. Egestas sed sed risus pretium quam vulputate dignissim. Justo laoreet sit amet cursus sit amet dictum sit. Velit egestas dui id ornare. Ac ut consequat semper viverra nam libero justo laoreet. Elementum facilisis leo vel fringilla est. Semper eget duis at tellus at urna condimentum.

Adipiscing bibendum est ultricies integer quis auctor. Lacus viverra vitae congue eu consequat. Viverra ipsum nunc aliquet bibendum enim facilisis gravida neque convallis. At elementum eu facilisis sed odio morbi quis commodo odio. Vehicula ipsum a arcu cursus. Quam adipiscing vitae proin sagittis. Nulla porttitor massa id neque aliquam vestibulum morbi blandit cursus. Pellentesque habitant morbi tristique senectus et netus et malesuada. Dui vivamus arcu felis bibendum ut tristique et egestas. Molestie nunc non blandit massa enim nec dui nunc mattis. Blandit cursus risus at ultrices mi tempus. Lacus suspendisse faucibus interdum posuere lorem ipsum dolor sit amet.

Nec sagittis aliquam malesuada bibendum arcu vitae. Arcu dictum varius duis at. Dui accumsan sit amet nulla facilisi morbi tempus. Bibendum ut tristique et egestas quis ipsum. Sit amet dictum sit amet justo donec enim diam. Dolor sit amet consectetur adipiscing elit duis tristique sollicitudin nibh. Duis at consectetur lorem donec massa sapien faucibus et. Ultrices tincidunt arcu non sodales neque sodales ut etiam. Eget mauris pharetra et ultrices neque ornare. Diam maecenas sed enim ut sem viverra aliquet eget. Tempus egestas sed sed risus pretium quam. Vitae suscipit tellus mauris a diam maecenas sed. Egestas maecenas pharetra convallis posuere morbi leo urna molestie at. Eget magna fermentum iaculis eu non. Volutpat sed cras ornare arcu. Lacus sed viverra tellus in hac habitasse platea dictumst. Ipsum suspendisse ultrices gravida dictum fusce ut placerat orci nulla.

Quam quisque id diam vel quam elementum. Nisl nunc mi ipsum faucibus vitae. Feugiat sed lectus vestibulum mattis ullamcorper velit sed. Eu volutpat odio facilisis mauris sit amet massa vitae tortor. Consectetur libero id faucibus nisl tincidunt eget. Auctor augue mauris augue neque gravida in. Pulvinar sapien et ligula ullamcorper malesuada proin libero nunc consequat. Id aliquet lectus proin nibh. Malesuada nunc vel risus commodo viverra. Convallis convallis tellus id interdum velit laoreet id donec ultrices. Et odio pellentesque diam volutpat commodo sed egestas. In nibh mauris cursus mattis. Viverra justo nec ultrices dui sapien. Hendrerit dolor magna eget est lorem ipsum dolor sit. Aliquet nec ullamcorper sit amet risus nullam. Vestibulum sed arcu non odio euismod lacinia. Viverra aliquet eget sit amet tellus cras adipiscing enim eu. Sagittis eu volutpat odio facilisis mauris sit amet.

Aliquet enim tortor at auctor urna nunc id. Habitant morbi tristique senectus et netus. Ullamcorper malesuada proin libero nunc consequat. Semper risus in hendrerit gravida rutrum quisque non. Sed nisi lacus sed viverra tellus in hac habitasse. Eget magna fermentum iaculis eu non diam phasellus vestibulum. Ultricies integer quis auctor elit sed vulputate mi sit. In hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit. Lorem donec massa sapien faucibus et. Eu nisl nunc mi ipsum faucibus vitae aliquet nec. Faucibus vitae aliquet nec ullamcorper sit amet risus. Amet volutpat consequat mauris nunc congue. Aenean euismod elementum nisi quis eleifend quam adipiscing. Tortor at auctor urna nunc id cursus. Tortor posuere ac ut consequat semper viverra nam libero justo. Et netus et malesuada fames ac turpis egestas sed tempus. Arcu ac tortor dignissim convallis. Gravida arcu ac tortor dignissim. Eu lobortis elementum nibh tellus molestie nunc non. Ac turpis egestas integer eget aliquet nibh praesent tristique.

Pharetra convallis posuere morbi leo urna. At imperdiet dui accumsan sit amet nulla facilisi. Viverra tellus in hac habitasse platea dictumst vestibulum. Tellus orci ac auctor augue mauris augue neque gravida in. Ridiculus mus mauris vitae ultricies leo. Arcu ac tortor dignissim convallis aenean et tortor at risus. Tristique nulla aliquet enim tortor at auctor urna nunc. Eu nisl nunc mi ipsum. Aenean euismod elementum nisi quis eleifend. Ultrices neque ornare aenean euismod elementum nisi quis. Sed pulvinar proin gravida hendrerit. Purus semper eget duis at tellus at. A erat nam at lectus urna. Elementum integer enim neque volutpat ac tincidunt vitae semper. Justo donec enim diam vulputate ut pharetra sit amet aliquam. Tempus quam pellentesque nec nam. Facilisis magna etiam tempor orci eu lobortis elementum nibh tellus. Cras ornare arcu dui vivamus arcu felis bibendum ut. Convallis a cras semper auctor neque vitae tempus quam pellentesque. Enim nunc faucibus a pellentesque sit amet porttitor eget.

Natoque penatibus et magnis dis parturient. Rhoncus est pellentesque elit ullamcorper dignissim. Ut consequat semper viverra nam libero justo laoreet sit. Ipsum faucibus vitae aliquet nec ullamcorper sit amet risus. Nec tincidunt praesent semper feugiat. Neque ornare aenean euismod elementum nisi quis eleifend. Justo donec enim diam vulputate ut pharetra sit amet aliquam. Fringilla est ullamcorper eget nulla facilisi etiam dignissim diam quis. Sit amet aliquam id diam maecenas ultricies mi eget mauris. Donec adipiscing tristique risus nec feugiat in fermentum posuere. Penatibus et magnis dis parturient montes nascetur ridiculus mus mauris. Quam adipiscing vitae proin sagittis nisl. Ante in nibh mauris cursus mattis. Sed cras ornare arcu dui. Commodo quis imperdiet massa tincidunt nunc pulvinar sapien et ligula. Leo duis ut diam quam nulla. Pharetra et ultrices neque ornare. Ut etiam sit amet nisl purus in. Arcu risus quis varius quam quisque id diam.

Auctor eu augue ut lectus arcu bibendum at varius. Aliquam nulla facilisi cras fermentum odio eu feugiat pretium nibh. Amet facilisis magna etiam tempor orci eu. Facilisi morbi tempus iaculis urna id. Arcu ac tortor dignissim convallis aenean et. Scelerisque purus semper eget duis. Magna etiam tempor orci eu lobortis elementum nibh tellus molestie. Tristique senectus et netus et malesuada. Eget est lorem ipsum dolor. Neque convallis a cras semper auctor neque vitae. Sed risus pretium quam vulputate dignissim suspendisse in est ante.

Sed id semper risus in hendrerit gravida rutrum quisque. Dolor sed viverra ipsum nunc aliquet bibendum enim. Faucibus a pellentesque sit amet porttitor eget. Consequat ac felis donec et odio. Nec feugiat in fermentum posuere urna nec tincidunt praesent. Ultrices mi tempus imperdiet nulla malesuada. Magnis dis parturient montes nascetur. Dictumst vestibulum rhoncus est pellentesque. Euismod in pellentesque massa placerat duis ultricies. Lectus mauris ultrices eros in. A condimentum vitae sapien pellentesque habitant. Libero nunc consequat interdum varius sit amet mattis vulputate enim. Ornare arcu dui vivamus arcu felis bibendum ut.

At varius vel pharetra vel turpis. Amet porttitor eget dolor morbi non arcu. Erat velit scelerisque in dictum. Tempus imperdiet nulla malesuada pellentesque elit eget. Augue mauris augue neque gravida in fermentum et sollicitudin ac. Nibh sit amet commodo nulla facilisi nullam. Aliquet porttitor lacus luctus accumsan tortor posuere. Gravida rutrum quisque non tellus. Dictum sit amet justo donec enim diam vulputate. Cras pulvinar mattis nunc sed. Et malesuada fames ac turpis. Dui id ornare arcu odio ut sem.

Orci porta non pulvinar neque laoreet suspendisse interdum. Non nisi est sit amet. Maecenas ultricies mi eget mauris. Sodales ut etiam sit amet nisl purus. Maecenas pharetra convallis posuere morbi leo urna molestie at elementum. Enim ut tellus elementum sagittis vitae. Cras ornare arcu dui vivamus arcu felis. Dui ut ornare lectus sit amet est placerat in egestas. Cursus mattis molestie a iaculis at erat pellentesque. Eget nunc lobortis mattis aliquam faucibus purus in massa. Morbi leo urna molestie at elementum eu facilisis sed odio. Egestas erat imperdiet sed euismod nisi porta lorem mollis aliquam. Egestas fringilla phasellus faucibus scelerisque eleifend.

Quis commodo odio aenean sed adipiscing diam donec. Porttitor massa id neque aliquam vestibulum morbi blandit. Diam sit amet nisl suscipit adipiscing bibendum est ultricies integer. Diam vel quam elementum pulvinar etiam. Sem nulla pharetra diam sit amet nisl suscipit adipiscing bibendum. Amet aliquam id diam maecenas ultricies mi. Tempus quam pellentesque nec nam aliquam sem et tortor. Eget dolor morbi non arcu risus quis varius quam. Id volutpat lacus laoreet non curabitur gravida arcu ac tortor. In vitae turpis massa sed elementum tempus. Nulla posuere sollicitudin aliquam ultrices sagittis orci a scelerisque. Lectus mauris ultrices eros in cursus turpis massa tincidunt. Commodo sed egestas egestas fringilla phasellus faucibus scelerisque eleifend donec. Pellentesque massa placerat duis ultricies lacus sed turpis. Odio eu feugiat pretium nibh ipsum consequat nisl vel. Augue ut lectus arcu bibendum at varius. Mauris vitae ultricies leo integer malesuada nunc vel risus. Mauris nunc congue nisi vitae. Diam in arcu cursus euismod quis viverra nibh.

Quam nulla porttitor massa id neque aliquam vestibulum morbi. Erat pellentesque adipiscing commodo elit at. Quam viverra orci sagittis eu volutpat odio facilisis. Ultrices dui sapien eget mi. Fermentum odio eu feugiat pretium nibh ipsum consequat nisl vel. Venenatis a condimentum vitae sapien pellentesque habitant morbi tristique. Odio tempor orci dapibus ultrices in. Metus aliquam eleifend mi in nulla posuere. Tristique senectus et netus et malesuada fames ac turpis egestas. Venenatis cras sed felis eget velit. Vitae ultricies leo integer malesuada nunc vel risus commodo viverra. Porttitor lacus luctus accumsan tortor posuere ac ut consequat. Tellus in hac habitasse platea dictumst vestibulum rhoncus. Non enim praesent elementum facilisis leo. Quam pellentesque nec nam aliquam sem. Tristique senectus et netus et malesuada fames ac turpis. Eros donec ac odio tempor orci dapibus ultrices. Tristique senectus et netus et malesuada. Cras ornare arcu dui vivamus arcu.</h1>
	</div>
	);
}
